#command: sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000  --rfsim --rfsimulator.serveraddr 127.0.0.6 --rfsimulator.serverport 4044 --sa -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/UE2_med.conf
#multi-ue comm: sudo ./multi-ue -r 1 "./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 --rfsim --rfsimulator.serveraddr 10.202.1.100 --rfsimulator.serverport 4044 --sa -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/UE2_MED.conf"
uicc0 = {
imsi = "001010000000001";
key = "465B5CE8B199B49FAA5F0A2EE238A6BC";
opc= "E8ED289DEBA952E4283B54E88E6183CA";
dnn= "internet";
nssai_sst=1;
nssai_sd=000001;
}