#command: sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000  --rfsim --rfsimulator.serveraddr 127.0.0.5 --rfsimulator.serverport 4043 --sa -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/UE_MED.conf
#multi_ue command: sudo ./multi-ue -r 1 "./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 --rfsim --rfsimulator.serveraddr 10.201.1.100 --rfsimulator.serverport 4043 --sa -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/UE_MED.conf"
uicc0 = {
imsi = "001010000060592";
key = "1B9DC14B6E16A8FE83AA0E8A0AB56FCB";
opc= "8CD505786285C50FEC35AD9D328816EA";
dnn= "internet";
nssai_sst=1;
nssai_sd=000001;
}